#Testes tentando setar variáveis de ambiente através do values.yaml

extraEnv:      
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: eurekatest
  NIVEL_LOG_APP: debug
  NIVEL_LOG_CONFIG: debug
  NIVEL_LOG_NETFLIX: warn
  NIVEL_LOG_WEB: warn
  PORTA: '8080'
  SPRING_CLOUD_CONFIG_SERVER_GIT_PASSWORD: 'example'
  SPRING_CLOUD_CONFIG_SERVER_GIT_URI: teste
  SPRING_CLOUD_CONFIG_SERVER_GIT_USER: teste
